package org.cohbe.ssa.rules;

import co.drools.model.*;

rule "Highest Score in Maths"
lock-on-active true
dialect "mvel"
dialect "java"
salience 6
when
		$sc : SeniorClass();
		$stList : Students(maths > 90)
		        from $sc.getStud();
then
        $sc.setHighScorerMath($stList.getName());
        update($sc)
		System.out.println(" Rule 1: Maths score");
end

rule "Highest Score in English"
lock-on-active true
dialect "mvel"
dialect "java"
salience 5
when
		$sc : SeniorClass();
		$stList : Students(english > 90)
		        from $sc.getStud();
then
        $sc.setHighScorerEnglish($stList.getName());
        update($sc)
		System.out.println(" Rule 2: English Score");
end

rule "Highest Score in Chemistry"
lock-on-active true
dialect "mvel"
dialect "java"
salience 4
when
		$sc : SeniorClass();
		$stList : Students(chemistry > 90)
		        from $sc.getStud();
then
        $sc.setHighScorerChemistry($stList.getName());
        update($sc)
		System.out.println(" Rule 3: Chemistry Score: " + $stList.getName());
end

rule "Highest Score in Physics"
lock-on-active true
dialect "mvel"
dialect "java"
salience 3
when
		$sc : SeniorClass();
		$stList : Students(physics > 90)
		        from $sc.getStud();
then
        $sc.setHighScorerPhysics($stList.getName());
        update($sc)
		System.out.println(" Rule 4: Physics Score");
end

rule "Total no. of Students passed"
lock-on-active true
dialect "mvel"
dialect "java"
salience 2
when
		$sc : SeniorClass();
		$stList : Students(physics > 40, chemistry > 40, english > 40, maths > 40)
		        from $sc.getStud();
then
        $sc.setStudentPassCount($sc.getStudentPassCount()+1);
        update($sc)
		System.out.println(" Rule 5: Total no. of Students passed");
end

rule "Students passed count"
no-loop true
dialect "mvel"
dialect "java"
salience 1
when
		$sc : SeniorClass(studentPassCount > 0);		
then
		
			System.out.println(" Rule 6: Total no. of Students passed are: " + $sc.getStudentPassCount());
		
end

rule "Students passed count with"
lock-on-active true
dialect "mvel"
dialect "java"
salience 110
when
		$sc : SeniorClass(studentPassCount==0);
then
		System.out.println(" Rule 7: Total no. of Students passed are: " + $sc.getStudentPassCount());
end